# Generated by Django 2.2.6 on 2019-11-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='telegram_username',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
