# Generated by Django 2.2.6 on 2019-10-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='comments',
            field=models.ManyToManyField(null=True, to='core.ResourceComment'),
        ),
    ]
