# Generated by Django 2.2.6 on 2019-10-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191025_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='comments',
            field=models.ManyToManyField(to='core.ResourceComment'),
        ),
    ]
